# Generated by Django 2.0.7 on 2018-08-14 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20180809_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapmessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flong', models.CharField(max_length=100)),
                ('Flati', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Daily_output', models.CharField(max_length=100)),
                ('Total_output', models.CharField(max_length=100)),
                ('Out_power', models.CharField(max_length=100)),
                ('Error', models.CharField(max_length=50)),
            ],
        ),
    ]
