# Generated by Django 2.0.7 on 2018-08-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_n', models.CharField(max_length=100)),
                ('name_sn', models.CharField(max_length=100)),
                ('name_pn', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('protocol', models.CharField(max_length=100)),
                ('belong_p', models.CharField(max_length=100)),
                ('belong_o', models.CharField(max_length=100)),
            ],
        ),
    ]
