# Generated by Django 2.0.7 on 2018-09-12 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_user_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='电站业主', max_length=100),
        ),
    ]
