from django.conf.urls import url,include
from .import views


urlpatterns = [
    url(r'^login/$', views.login),
    url(r'^logout/$', views.logout),
    url(r'^regist/$', views.regist),
    url(r'^gaode/$', views.gaode),
    url(r'^gaode1/$', views.gaode1),
    url(r'^xiala/$', views.xiala),
    url(r'^classes/$', views.classes),
    url(r'^addclass/$', views.addclass),
    url(r'^delclass/$', views.delclass),
    url(r'^editclass/$', views.editclass),
    url(r'^ /$', views.teacher),
    url(r'^addteacher/$', views.addteacher),
    url(r'^delteacher/$', views.delteacher),
    url(r'^editteacher/$', views.editteacher),
    url(r'^students/$', views.students),
    url(r'^addstudent/$', views.addstudent),
    url(r'^editstudent/$', views.editstudent),
    url(r'^modal_add_class/$', views.modal_add_class),
    url(r'^modal_edit_class/$', views.modal_edit_class),
    url(r'^modal_add_student/$', views.modal_add_student),
    url(r'^modal_edit_student/$', views.modal_edit_student),
    url(r'^test/$', views.test),
    url(r'^test1/$', views.test1),
    url(r'^jicheng/$', views.jicheng),
    url(r'^shebei/$', views.shebei),
    url(r'^modal_add_shebei/$', views.modal_add_shebei),
    url(r'^modal_edit_shebei/$', views.modal_edit_shebei),
    url(r'^delshebei/$', views.delshebei),
    url(r'^xinxi/$', views.xinxi),
    url(r'^daily/$', views.daily),
    url(r'^power/$', views.power),
    url(r'^month/$', views.month),
    url(r'^year/$', views.year),
    url(r'^empty/$', views.empty),
    url(r'^csrf1/$', views.csrf1),
    url(r'^template1/$', views.template1),
    url(r'^session_login/$', views.session_login),
    url(r'^session_success/$', views.session_success),
    url(r'^shebei_jicheng/$', views.shebei_jicheng),
    url(r'^user_managet/$', views.user_managet),
    url(r'^modal_add_user/$', views.modal_add_user),
    url(r'^modal_edit_user/$', views.modal_edit_user),
    url(r'^deluser/$', views.deluser),
    url(r'^modal_edit_password/$', views.modal_edit_password),
    url(r'^Alarm/$', views.Alarm),

]